config/routes.rb
Temp::Application.routes.draw do

  root :to => "topics#index", via: [:get]
  resources :topics do
    member do
      get :delete
    end
    resources :comments do
      member do
        get :delete
      end
    end
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document

  field :name,          type: String
  field :content,       type: String
  belongs_to :topic, :inverse_of => :comments

end

app/models/topic.rb
class Topic

  include Mongoid::Document

  field :name, type: String
  field :title, type: String
  field :content, type: String

  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @topic = Topic.find(params[:topic_id])
    @comment = Comment.new
    @title = "New Comment"
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.build(comment_params)
      if @comment.save
        flash[:notice] = "Comment added successfully!"
        redirect_to(topic_path(@topic.id))
      else
        flash[:notice] = "Error creating comment!"
        render 'new'
      end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments(params[:id])
    @title = "Edit Comment"
  end
  def update
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      flash[:notice] = "Comment updated successfully!"
      redirect_to(topic_path(@topic.id))
    else
      flash[:notice] = "Error updating comment!"
      render 'edit'
    end
  end

  def delete
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.find(params[:id])
    @title = "Delete Comment"
  end

  def destroy
    topic = Topic.find(params[:topic_id])
    comment = topic.comments(params[:id])
    comment.destroy
    flash[:notice] = "Comment deleted successfully!"
    redirect_to(topic_path(params[:id]))
  end
  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.order("id ASC")
    @title = "Forum"
  end
  def new
    @topic = Topic.new
    @title = "New Topic"
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:notice] = "Topic created successfully!"
      redirect_to(topic_path(@topic.id))
    else
      flash[:notice] = "Error creating topic!"
      render 'new'
    end
  end
  def show
    @topic = Topic.find(params[:id])
    @title = @topic.title
  end

  def edit
    @topic = Topic.find(params[:id])
    @title = "Edit Topic"
  end

  def update
    @topic = Topic.find(params[:id])
      if @topic.update_attributes(topic_params)
        flash[:notice] = "Topic updated successfully!"
        redirect_to(topic_path(@topic.id))
      else
        flash[:notice] = "Error updating topic!"
        render 'edit'
      end
  end

  def delete
    @topic = Topic.find(params[:id])
    @title = "Delete Topic"
  end

  def destroy
    topic = Topic.find(params[:id])
    topic.destroy
    flash[:notice] = "Topic '#{topic.title}' deleted successfully!"
    redirect_to(:action => 'index')
  end

  private
    def topic_params
      params.require(:topic).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/views/comments/delete.html.erb
<%= link_to 'Back', topic_path(@topic.id), :class => 'btn btn-success' %><br /><br />
<div class="col-sm-6 show-topic">
<%= form_tag({:action => 'destroy', :id => @topic.id}, :method => 'Delete') do %>
      <input type="hidden" name="id" id="id" value="<%= @comment.id %>" />
      <h2>Delete comment</h2>
      <p>Are you sure you want to delete the following comment?</p>
      <blockquote>
        <%= @comment.content %>
      </blockquote>
      <%= submit_tag("Confirm", :class => 'btn btn-danger') %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= link_to 'Back', topic_path(@topic.id), :class => 'btn btn-success' %><br /><br />
<div class="col-sm-12 show-topic">
  <h2 class="col-sm-10 col-sm-offset-3">Update comment</h2><br />
<%= form_for @comment, url: topic_comment_path(params[:topic_id], params[:id]),
             :html => {:id => 'edit-topic-form', :class => 'form-horizontal col-sm-6 col-sm-offset-2'} do |f| %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :content, class: 'form-control', size: '24x6', placeholder: 'Write about the topics here...'  %>
      </div>
    </div>

    <div class="form-group">
      <%= submit_tag("Update", :class => 'col-sm-offset-5 btn btn-primary') %>
      <%= link_to 'Delete', delete_topic_comment_path(params[:topic_id], params[:id]), :class => 'btn btn-danger' %>
    </div>
<% end %>
</div>

app/views/comments/new.html.erb
<%= link_to 'Back', topic_path(@topic.id), :class => 'btn btn-success' %><br /><br />
<div class="col-sm-12 show-topic">
  <h2 class="col-sm-10 col-sm-offset-3">Create a new comment</h2><br />
    <%= form_for(:comment, :url => {:action => 'create'},
                 :html => {:id => 'edit-topic-form', :class => 'form-horizontal col-sm-6 col-sm-offset-2'}) do |f| %>

        <input type="hidden" name="topic_id" id="topic_id" value="<%= @topic.id %>" />
        <div class="form-group">
          <%= f.label :name, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :content, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_area :content, class: 'form-control', size: '24x6', placeholder: 'Write about the topics here...'  %>
          </div>
        </div>

        <div class="form-group">
          <%= submit_tag("Submit", :class => 'col-sm-offset-5 btn btn-primary') %>
        </div>
    <% end %>
</div>

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag "jquery.min", "data-turbolinks-track" => true %>
<%=
    #javascript_include_tag "underscore-min", "data-turbolinks-track" => true
%>
<%=
    #javascript_include_tag "backbone-min", "data-turbolinks-track" => true
%>
<%=
    #javascript_include_tag "Backbone-relational", "data-turbolinks-track" => true
%>
<%=
    #javascript_include_tag "forum", "data-turbolinks-track" => true
%>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "bootstrap", media: "screen", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "custom", "data-turbolinks-track" => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails Forum | <%= @title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= render 'layouts/javascripts' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="col-lg-12 main">
    <div class="ccc col-lg-10 col-lg-offset-1 top clearfix">
      <div class="logo col-sm-2">
        <%= link_to image_tag("logo.jpg", :attr => 'Ruby on Rails Forum',
                    :alt => 'Ruby on Rails Forum', :class => 'round'),
            root_path %>
      </div>
      <div class="heading col-sm-10">
        <h3>One Stop portal for all that relates to Ruby on Rails and MongoDB</h3>
      </div>
    </div>
    <div class="ccc col-lg-10 col-lg-offset-1 mid clearfix">
      <%= yield %>
    </div>
    <div class="ccc col-lg-10 col-lg-offset-1 bottom">
      <footer>
        &copy;Copyright <%= Time.now.year %>, RoR Forum
      </footer>
    </div>
  </div>
</div>
</body>
</html>

app/views/topics/delete.html.erb
<%= link_to 'Back', topic_path(@topic.id), :class => 'btn btn-success' %><br /><br />
<div class="col-sm-6 show-topic">
  <%= form_tag({:action => 'destroy', :id => @topic.id}, :method => 'Delete') do %>
  <h2>Delete topic</h2>
  <p>Are you sure you want to delete the following topic?</p>
    <blockquote>
      <%= @topic.title %>
    </blockquote>
  <%= submit_tag("Confirm", :class => 'btn btn-danger') %>
  <% end %>
</div>

app/views/topics/edit.html.erb
<%= link_to 'Back', topic_path(@topic.id), :class => 'btn btn-success' %><br /><br />
<div class="col-sm-12 show-topic">
<h2 class="col-sm-offset-5">Update topic</h2><br />
<%= form_for @topic, url: topic_path(@topic.id),
             :html => {:id => 'edit-topic-form', :class => 'form-horizontal col-sm-6 col-sm-offset-3'} do |f| %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Title'  %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :content, class: 'form-control', size: '24x6', placeholder: 'Write about the topics here...'  %>
      </div>
    </div>

    <div class="form-group">
      <%= submit_tag("Update", :class => 'col-sm-offset-5 btn btn-primary') %>
      <%= link_to 'Delete', delete_topic_path(@topic.id), :class => 'btn btn-danger' %>
    </div>
<% end %>
</div>

app/views/topics/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="bg-success text-center">
      <p><%= flash[:notice] %></p>
    </div>
<% end %>
<%= link_to 'Create Topic', new_topic_path(), :class => 'btn btn-primary pull-right btn-md' %>
<br /><br />
<div class="list-topics col-sm-12 clearfix">
<% @topics.any? { %>
  <table class="table">
      <thead>
      <tr>
        <th>Topic</th>
        <th>Created By</th>
      </tr>
      </thead>
      <tbody>
      <% @topics.each do |topic| %>
        <tr>
          <td><%= link_to topic.title, topic_path(topic.id) %></td>
          <td><%= topic.name %></td>
        </tr>
      <% end %>
      </tbody>
  </table>
<% } %>
</div>

app/views/topics/new.html.erb
<%= link_to 'Back', root_path, :class => 'btn btn-success' %><br /><br />
<div class="col-sm-12 show-topic">
  <h2 class="col-sm-10 col-sm-offset-3">Create a new topic</h2><br />
<%= form_for(:topic, :url => {:action => 'create'},
             :html => {:id => 'edit-topic-form', :class => 'form-horizontal col-sm-6 col-sm-offset-2'}) do |f| %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Title'  %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :content, class: 'form-control', size: '24x6', placeholder: 'Write about the topics here...'  %>
      </div>
    </div>

    <div class="form-group">
      <%= submit_tag("Create Topic", :class => 'col-sm-offset-5 btn btn-primary') %>
    </div>
<% end %>
</div>

app/views/topics/show.html.erb
<% if !flash[:notice].blank? %>
    <div class="bg-success text-center">
      <p><%= flash[:notice] %></p>
    </div>
<% end %>
 <%= link_to 'Back', root_path, :class => 'btn btn-success' %><br /><br />
<div class="show-topic col-lg-12">
<div class="topic">
  <h2><%= @topic.title %></h2> - <i><%= @topic.name %></i>
  <%= link_to 'Edit', edit_topic_path(@topic.id), :class => 'btn btn-info btn-sm pull-right' %>
  <blockquote>
    <%= @topic.content %>
  </blockquote>
</div>
  <%= link_to 'Comment', new_topic_comment_path(@topic.id), :class => 'btn btn-primary btn-sm' %>
  <% @topic.comments.any? { %>
      <div class="topic_reponse">
        <% (@topic.comments).each do |comment| %>
            <div class="comments">
                <%= link_to 'Edit', edit_topic_comment_path(@topic.id, comment.id), :class => 'btn btn-primary btn-xs pull-right' %>
                <b><%= comment.name %></b>
                <p><%= comment.content %></p>
            </div>
        <% end %>
      </div>
      <% } %>
</div>